name: Release

on:
  pull_request:
  push:
    tags:
      - v*

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/build_cxx_sysroot.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: wasix-sysroot

      - name: Publish
        run: |
          ls -alsh
          ls wasix-sysroot -alsh
          mkdir publish
          tar xcf publish/sysroot.tar.gz wasix-sysroot
          ls -alsh
          ls -alsh publish
          echo so far, so good
